export const USER_DATA = [
  {
    number: 1,
    firstName: 'Tomas',
    lastName: 'Paul',
    city: 'Pittsburgh',
    phone: '412-202-7837',
    email: 'tomas_paul@mail.com',
  },
  {
    number: 2,
    firstName: 'Hanna',
    lastName: 'Bishop',
    city: 'Jacksonville',
    phone: '217-461-0535',
    email: 'hanna_bishop@mail.com',
  },
  {
    number: 3,
    firstName: 'Derick',
    lastName: 'Robertson',
    city: 'Philadelphia',
    phone: '215-332-9775',
    email: 'derik_robertson@mail.com',
  },
  {
    number: 4,
    firstName: 'Tobias',
    lastName: 'McCarthy',
    city: 'Indianapolis',
    phone: '317-213-7224',
    email: 'tobias_mccarthy@mail.com',
  },
  {
    number: 5,
    firstName: 'Kristin',
    lastName: 'Hopkins',
    city: 'Stockton',
    phone: '207-567-5286',
    email: 'kristin_stockton@mail.com',
  },
  {
    number: 6,
    firstName: 'Margaret',
    lastName: 'Rice',
    city: 'Albuquerque',
    phone: '505-228-3761',
    email: 'margaret_rice@mail.com',
  },
  {
    number: 7,
    firstName: 'William',
    lastName: 'Chapman',
    city: 'Huntington',
    phone: '260-355-8206',
    email: 'william_chapman@mail.com',
  },
  {
    number: 8,
    firstName: 'Carol',
    lastName: 'Barnett',
    city: 'Detroit',
    phone: '248-228-0770',
    email: 'carol_barnett@mail.com',
  },
  {
    number: 9,
    firstName: 'Oliver',
    lastName: 'West',
    city: 'Honolulu',
    phone: '808-227-1451',
    email: 'oliver_west@mail.com',
  },
  {
    number: 10,
    firstName: 'Maria',
    lastName: 'Sanders',
    city: 'Arlington',
    phone: '224-409-3225',
    email: 'maria_sanders@mail.com',
  },
];
